name: Main Push
env:
  HUSKY: 0
on:
  push:
    branches:
      - main
      - main-test
jobs:
  is-pushing-new-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.is-new-version-step.outputs.new-version }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - id: is-new-version-step
        run: |
          if [[ $(git log -1 --pretty=format:"%B") = *new-version:* ]];
          then echo "new-version=true" >> "$GITHUB_OUTPUT";
          echo hello;
          fi
  make-prerelease-version-regular:
    runs-on: ubuntu-latest
    needs: is-pushing-new-version
    if: ${{ needs.is-pushing-new-version.outputs.new-version == 'true' }}
    permissions:
      contents: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          fetch-tags: true
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run make-prerelease-regular
      - run: git config --global user.email "from-workflow@email.com"
      - run: git config --global user.name "Workflow Bot"
      - run: git add package.json
      - run: git commit --amend --no-edit
      - run: git push origin --force-with-lease
      - run: gh release create "v$(npm pkg get version | sed "s/[\'\"]//g")" --target=$(git branch --show-current)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
