name: Main Pull Request
env:
  HUSKY: 0
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - main-test
jobs:
  test:
    uses: ./.github/called-workflows/test.yml
    with:
      branch_ref: ${{ github.head_ref }}
  is-prerelease-version-valid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{  github.head_ref  }}
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run is-prerelease-version-valid
