name: Prerelease Pull Request
env:
  HUSKY: 0
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - prerelease
      - development
jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      branch_ref: ${{ github.head_ref}}
