name: Build and test the utility function then publish package to npm
on:
  release:
    types: [published]
jobs:
  test:
    uses: ./.github/called-workflows/test.yml
    with:
      branch_ref: ${{ github.ref }}
  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm build
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
